### ISSUE TITLE
v 1.2 broken in Firefox?

### ISSUE THREAD

**Issue by NoLooseEnds** [pawelmalak/flame#23]
It works in Safari, but not in Firefox and Chrome. I use Traefik as a proxy, and I think that could be the reason, but this issue what not present in the previous version. 

Firefox:
```
DOMException: The operation is insecure. react-dom.production.min.js:216:199
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    F scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    (Async: EventHandlerNonNull)
    <anonymous> scheduler.production.min.js:12
    l (index):1
    <anonymous> index.js:4
    l (index):1
    <anonymous> React
    l (index):1
    <anonymous> React
    l (index):1
    144 main.6f693952.chunk.js:1
    l (index):1
    r (index):1
    t (index):1
    <anonymous> main.6f693952.chunk.js:1


Uncaught DOMException: The operation is insecure. main.6f693952.chunk.js:1
    We WeatherWidget.tsx:53
    Bi React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    F scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    (Async: EventHandlerNonNull)
    <anonymous> scheduler.production.min.js:12
    l (index):1
    <anonymous> index.js:4
    l (index):1
    <anonymous> React
    l (index):1
    <anonymous> React
    l (index):1
    144 main.6f693952.chunk.js:1
    l (index):1
    r (index):1
    t (index):1
    <anonymous> main.6f693952.chunk.js:1
```

Chrome:
```
WeatherWidget.tsx:53 Mixed Content: The page at 'https://flame.hostname.tld/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://flame.hostname.tld/socket'. This request has been blocked; this endpoint must be available over WSS.
(anonymous) @ WeatherWidget.tsx:53
react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at https://flame.hostname.tld/static/js/main.6f693952.chunk.js:1:14327
    at Bi (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:171725)
    at H.unstable_runWithPriority (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:189537)
    at jL (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:111896)
    at Pi (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:171186)
    at https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:171097
    at F (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:188596)
    at MessagePort.p.port1.onmessage (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:187318)
er @ react-dom.production.min.js:216
scheduler.production.min.js:12 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at https://flame.hostname.tld/static/js/main.6f693952.chunk.js:1:14327
    at Bi (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:171725)
    at H.unstable_runWithPriority (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:189537)
    at jL (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:111896)
    at Pi (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:171186)
    at https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:171097
    at F (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:188596)
    at MessagePort.p.port1.onmessage (https://flame.hostname.tld/static/js/2.6b40f2c2.chunk.js:2:187318)
```

Safari, works, but gives this:
```
[Warning] [blocked] The page at https://flame.hostname.tld/ was not allowed to run insecure content from ws://flame.hostname.tld/socket. (main.6f693952.chunk.js, line 1)

```

**Comment by pawelmalak** [comment]
This issue wasn't present in the previous version because websocket was broken back then and wasn't connecting at all. 

After quick googling it seems that Firefox is blocking insecure websockets connections with ws:// protocol. 

I'll investigate it and either fix it or scrap use of websockets for now.
