### ISSUE TITLE
[BUG] SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by odinsride** [pawelmalak/flame#324]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.2.1
- Platform [e.g. amd64, arm64, arm/v7]:  amd64
- Docker image tag [e.g. latest, multiarch]: latest

---

**Bug description:**

When navigating to my flame dashboard URL, I am getting this in the log file. This happened after uninstalling and reinstalling docker on OpenSUSE Leap

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at initConfig (/app/utils/init/initConfig.js:13:29)
    at async initApp (/app/utils/init/index.js:8:3)
    at async /app/server.js:23:3
undefined:1
```

---

**Steps to reproduce:**

**Comment by odinsride** [comment]
Nevermind. Something on my end was messed up. Restored config.json from a backup and back in business
