### ISSUE TITLE
WebSocket crash on latest docker image

### ISSUE THREAD

**Issue by burntcookie90** [pawelmalak/flame#63]
[2021-07-10 16:49:49.577 UTC+0] [INFO] Connected to database,
[2021-07-10 16:49:49.578 UTC+0] [INFO] Starting model synchronization,
[2021-07-10 16:49:52.028 UTC+0] [INFO] All models were synchronized,
[2021-07-10 16:49:52.038 UTC+0] [INFO] Initial config created,
[2021-07-10 16:49:52.040 UTC+0] [INFO] Socket: listen,
[2021-07-10 16:49:52.040 UTC+0] [INFO] Server is running on port 5005 in production mode,
events.js:352,
      throw er; // Unhandled 'error' event,
      ^,
,
RangeError: Invalid WebSocket frame: invalid status code 22373,
    at Receiver.controlMessage (/app/node_modules/ws/lib/receiver.js:464:18),
    at Receiver.getData (/app/node_modules/ws/lib/receiver.js:350:42),
    at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:143:22),
    at Receiver._write (/app/node_modules/ws/lib/receiver.js:78:10),
    at writeOrBuffer (internal/streams/writable.js:358:12),
    at Receiver.Writable.write (internal/streams/writable.js:303:10),
    at Socket.socketOnData (/app/node_modules/ws/lib/websocket.js:909:35),
    at Socket.emit (events.js:375:28),
    at addChunk (internal/streams/readable.js:290:12),
    at readableAddChunk (internal/streams/readable.js:265:9),
Emitted 'error' event on WebSocket instance at:,
    at Receiver.receiverOnError (/app/node_modules/ws/lib/websocket.js:814:13),
    at Receiver.emit (events.js:375:28),
    at emitErrorNT (internal/streams/destroy.js:106:8),
    at emitErrorCloseNT (internal/streams/destroy.js:74:3),
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {,
  [Symbol(status-code)]: 1002,
},

`restart: on-failure` gets around this, but its a consistent crash.

**Comment by pawelmalak** [comment]
I cannot reproduce this issue. I have two instances running on latest tag for over 2 weeks without any errors. 

Which tag are you using? Are you getting this error immediately after server is started or only after you open frontend?

**Comment by burntcookie90** [comment]
i am on `latest`. It seems to happen immediately after opening the front end. I am using safari on ipadOS 15.

**Comment by pawelmalak** [comment]
Are you running flame behind reverse proxy by any chance?

**Comment by burntcookie90** [comment]
Yes, it's behind traefik

**Comment by pawelmalak** [comment]
Do you have websocket functionality enabled (#24)? Also are you getting the same error while visiting flame from desktop device/browser?

**Comment by burntcookie90** [comment]
Hm, I have been using this behind traefik for a month now. Multiple desktop machines with firefox/chrome, and my iOS devices (phone and ipad). I am only seeing this crash with the new safari in ipadOS 15. I wonder if the safari build on here is causing some weird issue. I dont have weather enabled, could that be causing the issue somehow? I will need to see if there's some specific fix for websockets+traefik that I can try later.

**Comment by pawelmalak** [comment]
I don't think enabling weather widget will change anything. Since you have it working on desktop browsers and it's working on my Safari on iOS 13.6.1 I think it's the problem with Safari build you are using. There's not much I can do about it.

**Comment by pawelmalak** [comment]
@burntcookie90 Can you check one thing? Open Flame on the device where it's not crashing e.g. desktop and in the settings set `Hide greeting and date` to `True`. Then open the app on the device where it does crash and check if it's still happening.

**Comment by burntcookie90** [comment]
Finally got around to testing this. Service seems to be staying up stable with this setting change.

**Comment by pawelmalak** [comment]
I build docker image with possible fix. You can pull it from `pawelmalak/flame:dev`. With that you shoud be able to set `Hide greeting and date` back to `False` and still have app working correctly with weather disabled.

**Comment by avandeputte** [comment]
following since I am also getting these errors.  No traefik,  all default settings on docker on unraid.


```
events.js:352
throw er; // Unhandled 'error' event

^

RangeError: Invalid WebSocket frame: invalid status code 22373
at Receiver.controlMessage (/app/node_modules/ws/lib/receiver.js:464:18)
at Receiver.getData (/app/node_modules/ws/lib/receiver.js:350:42)
at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:143:22)
at Receiver._write (/app/node_modules/ws/lib/receiver.js:78:10)
at writeOrBuffer (internal/streams/writable.js:358:12)
at Receiver.Writable.write (internal/streams/writable.js:303:10)
at Socket.socketOnData (/app/node_modules/ws/lib/websocket.js:909:35)
at Socket.emit (events.js:375:28)
at addChunk (internal/streams/readable.js:290:12)
at readableAddChunk (internal/streams/readable.js:265:9)
Emitted 'error' event on WebSocket instance at:

at Receiver.receiverOnError (/app/node_modules/ws/lib/websocket.js:814:13)
at Receiver.emit (events.js:375:28)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21) {
[Symbol(status-code)]: 1002
}
```

**Comment by pawelmalak** [comment]
Are you on the same version of Safari as @burntcookie90 ?

**Comment by avandeputte** [comment]
No, I use chrome

**Comment by pawelmalak** [comment]
Are you using weather module or is the api key field empty?

**Comment by avandeputte** [comment]
I am using the weather, and the API key is not empty.  Weather has been working fine for weeks.

**Comment by pawelmalak** [comment]
I'm using `latest` tag on my unraid server with default settings and I'm not able to reproduce this issue in any of the major browsers (Chrome, Firefox, Opera - all on the latest versions).
This issue needs further investigation.

**Comment by pawelmalak** [comment]
Closed due to inactivity
